Experiment 'pythonPromptNewToolsExt' is active
> conda info --json
Python interpreter path: /usr/bin/python3
[ERROR 2023-3-6 0:23:37.226]: readdir() failed for "/var/cache/ldconfig" (Error: EACCES: permission denied, scandir '/var/cache/ldconfig')
[ERROR 2023-3-6 0:23:37.254]: readdir() failed for "/var/cache/pollinate" (Error: EACCES: permission denied, scandir '/var/cache/pollinate')
[ERROR 2023-3-6 0:23:37.355]: readdir() failed for "/var/cache/private" (Error: EACCES: permission denied, scandir '/var/cache/private')
[ERROR 2023-3-6 0:23:37.448]: readdir() failed for "/var/lib/amazon" (Error: EACCES: permission denied, scandir '/var/lib/amazon')
[ERROR 2023-3-6 0:23:37.583]: readdir() failed for "/var/lib/polkit-1" (Error: EACCES: permission denied, scandir '/var/lib/polkit-1')
[ERROR 2023-3-6 0:23:37.584]: readdir() failed for "/var/lib/private" (Error: EACCES: permission denied, scandir '/var/lib/private')
[ERROR 2023-3-6 0:23:37.631]: readdir() failed for "/var/lib/udisks2" (Error: EACCES: permission denied, scandir '/var/lib/udisks2')
> /bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:23:37.652]: readdir() failed for "/var/log/amazon" (Error: EACCES: permission denied, scandir '/var/log/amazon')
[ERROR 2023-3-6 0:23:37.679]: readdir() failed for "/var/log/private" (Error: EACCES: permission denied, scandir '/var/log/private')
[ERROR 2023-3-6 0:23:37.682]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:23:37.759]: readdir() failed for "/var/spool/rsyslog" (Error: EACCES: permission denied, scandir '/var/spool/rsyslog')
[ERROR 2023-3-6 0:23:37.771]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-ModemManager.service-mp5qBi" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-ModemManager.service-mp5qBi')
[ERROR 2023-3-6 0:23:37.776]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-apache2.service-8zjWUh" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-apache2.service-8zjWUh')
[ERROR 2023-3-6 0:23:37.776]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-hostnamed.service-dyMwVg" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-hostnamed.service-dyMwVg')
[ERROR 2023-3-6 0:23:37.778]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-logind.service-F7V5Pi" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-logind.service-F7V5Pi')
[ERROR 2023-3-6 0:23:37.782]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-resolved.service-1A5QUe" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-resolved.service-1A5QUe')
> /usr/bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 0:23:37.808]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-timedated.service-GwblZh" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-timedated.service-GwblZh')
[ERROR 2023-3-6 0:23:37.813]: readdir() failed for "/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-timesyncd.service-xpCnIf" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-5f583dbaf63741e09f54b44665fb99c8-systemd-timesyncd.service-xpCnIf')
[ERROR 2023-3-6 0:23:37.828]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
Starting Pylance language server.
