Experiment 'pythonPromptNewToolsExt' is active
> conda info --json
Python interpreter path: /usr/bin/python3
[ERROR 2023-3-6 1:34:47.183]: readdir() failed for "/var/cache/ldconfig" (Error: EACCES: permission denied, scandir '/var/cache/ldconfig')
[ERROR 2023-3-6 1:34:47.184]: readdir() failed for "/var/cache/pollinate" (Error: EACCES: permission denied, scandir '/var/cache/pollinate')
[ERROR 2023-3-6 1:34:47.185]: readdir() failed for "/var/cache/private" (Error: EACCES: permission denied, scandir '/var/cache/private')
[ERROR 2023-3-6 1:34:47.188]: readdir() failed for "/var/lib/amazon" (Error: EACCES: permission denied, scandir '/var/lib/amazon')
[ERROR 2023-3-6 1:34:47.234]: readdir() failed for "/var/lib/polkit-1" (Error: EACCES: permission denied, scandir '/var/lib/polkit-1')
[ERROR 2023-3-6 1:34:47.235]: readdir() failed for "/var/lib/private" (Error: EACCES: permission denied, scandir '/var/lib/private')
> /bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 1:34:47.266]: readdir() failed for "/var/lib/udisks2" (Error: EACCES: permission denied, scandir '/var/lib/udisks2')
> /bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 1:34:47.288]: readdir() failed for "/var/log/amazon" (Error: EACCES: permission denied, scandir '/var/log/amazon')
[ERROR 2023-3-6 1:34:47.291]: readdir() failed for "/var/log/private" (Error: EACCES: permission denied, scandir '/var/log/private')
> /usr/bin/python -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 1:34:47.305]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 1:34:47.314]: Support for Python 2.7 has been dropped by the Python extension so certain features may not work, upgrade to using Python 3.
> /usr/bin/python ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
> /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2023.6.0/pythonFiles/interpreterInfo.py
[ERROR 2023-3-6 1:34:47.404]: readdir() failed for "/var/spool/rsyslog" (Error: EACCES: permission denied, scandir '/var/spool/rsyslog')
[ERROR 2023-3-6 1:34:47.414]: readdir() failed for "/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-ModemManager.service-5XfKif" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-ModemManager.service-5XfKif')
[ERROR 2023-3-6 1:34:47.417]: readdir() failed for "/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-apache2.service-ERbP1h" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-apache2.service-ERbP1h')
[ERROR 2023-3-6 1:34:47.418]: readdir() failed for "/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-systemd-logind.service-KEhn6g" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-systemd-logind.service-KEhn6g')
[ERROR 2023-3-6 1:34:47.418]: readdir() failed for "/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-systemd-resolved.service-3LBp4f" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-systemd-resolved.service-3LBp4f')
[ERROR 2023-3-6 1:34:47.420]: readdir() failed for "/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-systemd-timesyncd.service-avJCGg" (Error: EACCES: permission denied, scandir '/var/tmp/systemd-private-d2f3b458dcb24d559a900674e72c90f0-systemd-timesyncd.service-avJCGg')
Starting Pylance language server.
